[package]
name = "byhttp"
version = "0.1.0"
authors = ["Lohikar <lohikar@protonmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true

[dependencies]
lazy_static = "1.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = "0.12"

[dependencies.reqwest]
version = "0.9"
default-features = false
features = ["rustls-tls"]	# Cross-compiling openssl on Linux is unpleasant, but rustls doesn't require any bullshit
